name: Continuous Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  analyze_code:
    name: Execute Rubocop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Rubocop checks
        uses: gimenete/rubocop-action@1.0