name: Continuous Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  analyze_code:
    name: Execute Rubocop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.5
      - name: Execute Rubocop
        run: |
          gem install bundler
          bundle install --with=continuouse_testing --jobs 4 --retry 3
          bundle exec rubocop